### PR TITLE
Upload SDK bullseye binaries for 4.5.1500

### PR DESCRIPTION
**Pull request by alexrallen**

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@liat-grozovik Can you please review?

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
@alexrallen  Do we require these "static" named libs? I don't see them for buster
bin/bullseye/sx-acl-helper-dev-static_1.mlnx.4.5.1500_amd64.deb
bin/bullseye/sx-complib-dev-static_1.mlnx.4.5.1500_amd64.deb
bin/bullseye/sx-scew-dev-static_1.mlnx.4.5.1500_amd64.deb
bin/bullseye/sxd-libs-dev-static_1.mlnx.4.5.1500_amd64.deb
bin/bullseye/wjh-libs-dev-static_1.mlnx.4.5.1500_amd64.deb

**Comment by alexrallen** [comment]
I figured it was unwise to be selective in my uploading of these files. However, I am not aware of any targets we have in SONiC for these files.

**Comment by alexrallen** [comment]
Per internal discussions and investigation the static files are unnecessary and have been removed.

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@liat-grozovik Can you please review and sign off?

**Pull request merged**
